# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "45db2794b9ee31dcde5920b07ec1e14e"
name = "front-app"
handle = "front-app-3"
application_url = "https://vatican-stretch-forum-halloween.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://vatican-stretch-forum-halloween.trycloudflare.com/auth/callback",
  "https://vatican-stretch-forum-halloween.trycloudflare.com/auth/shopify/callback",
  "https://vatican-stretch-forum-halloween.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
